# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import lunch.models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20160923_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=lunch.models.two_hour_lag),
        ),
    ]
