# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import lunch.models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20160923_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(db_index=True, default=lunch.models.two_hour_lag),
        ),
    ]
