# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20160925_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
