# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_restaurant_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
